name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: Run tests
        type: choice
        options:
          - Run tests
          - test_login
          - test_successful_post_creation
          - test_validation_messages

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          Python-version: "3.12"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        if: "github.event.inputs.deployment_target == 'Run tests'"
        run: pytest test_page_object.py
      - name: test_login
        if: "github.event.inputs.deployment_target == 'test_login'"
        run: pytest test_page_object.py::TestWebSite::test_test_login
      - name: test_successful_post_creation
        if: "github.event.inputs.deployment_target == 'test_successful_post_creation'"
        run: pytest test_page_object.py::TestWebSite::test_post_creation
      - name: test_validation_messages
        if: "github.event.inputs.deployment_target == 'test_validation_messages'"
        run: pytest test_page_object.py::TestWebSite::test_validation_messages